name: CI Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build (${{ matrix.configuration }})
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "4.8.x"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore dependencies
        run: dotnet restore

      - name: Build ${{ matrix.configuration }}
        run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

      - name: Upload build artifacts (${{ matrix.configuration }})
        uses: actions/upload-artifact@v4
        with:
          name: ce-mcp-${{ matrix.configuration }}
          path: |
            bin/${{ matrix.configuration }}/
            !bin/${{ matrix.configuration }}/**/*.pdb
          retention-days: 7

      - name: List build output
        run: |
          echo "Build output for ${{ matrix.configuration }}:"
          dir bin\${{ matrix.configuration }} /s
        shell: cmd
